### PR TITLE
[tools] extended query cli lib

### PR DESCRIPTION
**Pull request by davidrotari19**
Extended query tool with get_events, get_transactions, common wallet migrated, common wallet pending payments, and common wallet signers.  The last 3 are commented out as at the moment any API to a common wallet returns an error.

### CODE REVIEW

**Comment by 0o-de-lally** [comment]
@davidrotari19 Thanks for this great first PR!

Some notes:
- make sure to rebase from `main` since there are more changes there since you started work.
- you should run cargo fmt and cargo clippy so that  the "cleanliness" CI tests pass.
- formal verification tests are not passing, but that's not your fault, there are patches to the workflow which you can get by rebasing from `main`

**Review by 0xzoz — APPROVED** [review]
This is awesome @davidrotari19! Looking forward to many more contributions

**Comment by 0xzoz** [comment]
@davidrotari19 could you please  run clippy and fmt then we will get this merged.

**Comment by kalvkusk** [comment]
@davidrotari19 please pull in changes from `main` for CI to pass

**Pull request closed without merging**
